### ISSUE TITLE
[Bug report]: generation of tokens not working as expected. seems that the “variables Import export” plugin for figma is broken. we used the "design token" plugin to generate the json file, but it seems that not all the tokens get generated. the generated css contains roughly 45 lines.

### ISSUE THREAD

**Issue by cmdillon** [ag-grid/ag-grid-figma-design-system#3] opened 2024-07-15 03:03 UTC
generation of tokens not working as expected. seems that the “variables Import export” plugin for figma is broken. we used the "design token" plugin to generate the json file, but it seems that not all the tokens get generated. the generated css contains roughly 45 lines.

**Comment by markdurrant** [comment] 2024-07-15 16:06
Hi @cmdillon. Thanks for your feedback! 

This project is explicitly designed to be used with the output of the [Design Tokens](https://www.figma.com/community/plugin/888356646278934516/design-tokens?searchSessionId=lyn6909j-lefnnh8czh) Figma plugin. There are other plugins that will export Figma variables. However they all use different formats so will not work with this project. 

The Design Tokens plugin currently has a [bug that affects variable referencing](https://github.com/lukasoppermann/design-tokens/issues/308). This is what breaks this project and causes the `Reference doesn't exist:` errors you are seeing. 

We are investigating if there is anything we can do on our side to mitigate the situation. We thank you for your patience.

**Comment by cmdillon** [comment] 2024-07-16 00:29
@markdurrant thx! for the speedy reply. since your documentation suggests that one can use token studio—why not use token studio's generator (https://github.com/tokens-studio/sd-transforms)?

**Comment by markdurrant** [comment] 2024-07-16 09:26
Hi @cmdillon. Whilst we definitely support Tokens Studio in the design system Figma, we're currently focusing on the local variables workflow for exporting tokens json. 

Thank you for your continued interest. We will update this issue when the issue is fixed within the [Design Tokens](https://github.com/lukasoppermann/design-tokens/issues/308) plugin, or if we find a solution on our side.

**Comment by markdurrant** [comment] 2024-07-17 10:24
This issue has been fixed with this [pull request](https://github.com/ag-grid/ag-grid-figma-design-system/pull/4). 


CSS generation should now work as expected with the default export of the current [Design Tokens](https://www.figma.com/community/plugin/888356646278934516) Figma plugin.

**Closed by markdurrant** 2024-07-17 10:24 UTC
